// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEIOg7XTVmNLohcOpgj5tyLtp1reBFveE',
    appId: '1:199416135988:web:4775dbadbe08f844d0a561',
    messagingSenderId: '199416135988',
    projectId: 'acadix-4a2d3',
    authDomain: 'acadix-4a2d3.firebaseapp.com',
    storageBucket: 'acadix-4a2d3.firebasestorage.app',
    measurementId: 'G-N2199WJ885',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqSR__wXoOONEcWcxtplrTdxzle6uX90',
    appId: '1:199416135988:android:8353ddfdf994b2fdd0a561',
    messagingSenderId: '199416135988',
    projectId: 'acadix-4a2d3',
    storageBucket: 'acadix-4a2d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGCaycE5KbUI6ZkJWR7jerz7dajOuElXE',
    appId: '1:199416135988:ios:956972d8a5fcf495d0a561',
    messagingSenderId: '199416135988',
    projectId: 'acadix-4a2d3',
    storageBucket: 'acadix-4a2d3.firebasestorage.app',
    iosBundleId: 'com.example.acadix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGCaycE5KbUI6ZkJWR7jerz7dajOuElXE',
    appId: '1:199416135988:ios:956972d8a5fcf495d0a561',
    messagingSenderId: '199416135988',
    projectId: 'acadix-4a2d3',
    storageBucket: 'acadix-4a2d3.firebasestorage.app',
    iosBundleId: 'com.example.acadix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEIOg7XTVmNLohcOpgj5tyLtp1reBFveE',
    appId: '1:199416135988:web:14abb13251dc5b03d0a561',
    messagingSenderId: '199416135988',
    projectId: 'acadix-4a2d3',
    authDomain: 'acadix-4a2d3.firebaseapp.com',
    storageBucket: 'acadix-4a2d3.firebasestorage.app',
    measurementId: 'G-JQ17JMJ8WB',
  );

}